# ===============================
# = Server Configuration
# ===============================
server.port=9099
spring.profiles.active=local
# ===============================
# Actuator
# ===============================
management.endpoints.web.exposure.include=health,info,metrics
management.endpoint.health.show-details=always